### ISSUE TITLE
Allow more than 1 user in the same room?

### ISSUE THREAD

**Issue by fera765** [ajayrwarrier/Video-Chat#1]
Type allows a maximum of 20 people in the same room?

**Comment by ajayrwarrier** [comment]
Type? What is that?

If you need more than 5 users in a room you'll need a media server.

**Comment by fera765** [comment]
So to make this implementation of 5 or more users in a zoom-style video room do you need a video server?

**Comment by fera765** [comment]
I tried to add more than 1 User to your project more successfully

I am trying to learn webrtc more ta kkk most of the materials and online courses are in English.  and I'm from Brazil I don't speak english kkk

**Comment by ajayrwarrier** [comment]
Yes, you need a server. You can either pay for one like Twilio or agora or you will have to build your own.

**Comment by fera765** [comment]
if i want to transmit only between 2 users as it is in your project and is it necessary to use a service like twilio?

**Comment by ajayrwarrier** [comment]
Or you would have to write all the backend logic of twilio.
